language: c

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2

install:
  - git clone https://github.com/berkmancenter/robustness_apache.git
  
script: 
  - sudo apxs -i -a -c mod_amber.c
